### ISSUE TITLE
daffodilTdmlUsesPackageBin does not work in IntelliJ

### ISSUE THREAD

**Issue by stevedlawrence** [apache/daffodil-sbt#29]
When `daffodilTdmlUsesPackageBin` is true, the plugin builds saved parsers and adds the saved parser directory to `Test/dependencyClasspath`. However, it seems like IntelliJ does not use this setting when building its test classpath, so TDML tests ran from IntelliJ cannot find the saved parsers.

@olabusayoT discovered that IntelliJ uses `Test/externalDependencyClasspath`, so we should add the directory to that instead.

As a temporary workaround, if you set `daffodilTdmlusesPackageBin` to true, then also add this to build.sbt:
```scala
Test / externalDependencyClasspath ++= Seq(target.value / "tdmlparsers")
```

**Comment by olabusayoT** [comment]
Just a note on the workaround: Test/externalDependencyClasspath doesn't actually work, but Test/unmanagedClasspath does. So

So adding the below to your build.sbt should suffice to get Intellij tests working with saved parsers

```sbt
Test / unmanagedClasspath ++= Seq(target.value / "tdmlparsers")
```
